spring:
  datasource:
    url: jdbc:mysql://database-1.cc3snbvcukcq.ap-southeast-1.rds.amazonaws.com/post_service?useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: sapassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: POST-SERVICE
  config:
      import: "optional:configserver:"
  cloud:
    config:
      uri: http://18.136.126.140:8888

#  redis:
#    hostname: localhost
#    password:
#    port: 6379
#    lettuce:
#      shutdown-timeout: 30000
#      pool:
#        max-active: 30
#        max-idle: 8
#        min-idle: 0
#eureka:
#  client:
#    registerWithEureka:
#      value: true
#    fetchRegistry:
#      value: true
#    instance:
#      hostname: 18.136.126.140
#    serviceUrl:
#      defaultZone: http://18.136.126.140:8761/eureka
server:
  port: 8001
